package org.romainlavabre.security;

/**
 * User attributes of an AWS Cognito identity.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface CognitoAttribute {
    /**
     * Generated by Cognito, immutable, it identifies the identity across the user pool.
     */
    String SUB = "sub";

    String EMAIL          = "email";
    String EMAIL_VERIFIED = "email_verified";
    String PHONE_NUMBER   = "phone_number";
}
