package org.romainlavabre.security.message;

/**
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface Error {
    String IDP_IDENTIFIER_REQUIRED = "IDP_IDENTIFIER_REQUIRED";
    String IDP_OTP_REQUIRED        = "IDP_OTP_REQUIRED";
    String IDP_NO_FLOW             = "IDP_NO_FLOW";
    String IDP_INVALID_CODE        = "IDP_INVALID_CODE";
    String IDP_LOGIN_INIT_FAILED   = "IDP_LOGIN_INIT_FAILED";
    String IDP_LOGIN_FAILED        = "IDP_LOGIN_FAILED";
    String IDP_NO_ACTIVE_SESSION   = "IDP_NO_ACTIVE_SESSION";
    String IDP_SESSION_EXPIRED     = "IDP_SESSION_EXPIRED";

    String IDP_USERNAME_REQUIRED        = "IDP_USERNAME_REQUIRED";
    String IDP_IDENTITY_ALREADY_EXISTS  = "IDP_IDENTITY_ALREADY_EXISTS";
    String IDP_IDENTITY_CREATION_FAILED = "IDP_IDENTITY_CREATION_FAILED";

    String IDP_FETCH_FAILED = "IDP_FETCH_FAILED";

    String IDP_IDENTITY_ID_REQUIRED = "IDP_IDENTITY_ID_REQUIRED";
    String IDP_IDENTITY_ID_INVALID  = "IDP_IDENTITY_ID_INVALID";
    String IDP_IDENTITY_FAILED      = "IDP_IDENTITY_FAILED";

    String IDP_CLIENT_ID_REQUIRED  = "IDP_CLIENT_ID_REQUIRED";
    String IDP_CLIENT_ID_INVALID   = "IDP_CLIENT_ID_INVALID";
    String IDP_HYDRA_CLIENT_FAILED = "IDP_HYDRA_CLIENT_FAILED";
}
