package org.romainlavabre.security.message;

/**
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface Error {
    String IDP_CLIENT_ID_REQUIRED    = "IDP_CLIENT_ID_REQUIRED";
    String IDP_CODE_REQUIRED         = "IDP_CODE_REQUIRED";
    String IDP_REDIRECT_URI_REQUIRED = "IDP_REDIRECT_URI_REQUIRED";
    String IDP_CLIENT_NOT_FOUND      = "IDP_CLIENT_NOT_FOUND";
    String IDP_EXCHANGE_CODE_FAILED  = "IDP_EXCHANGE_CODE_FAILED";
    String IDP_NO_ACTIVE_SESSION     = "IDP_NO_ACTIVE_SESSION";
    String IDP_REFRESH_FAILED        = "IDP_REFRESH_FAILED";
    String IDP_REVOKE_FAILED         = "IDP_REVOKE_FAILED";

    String IDP_USERNAME_REQUIRED        = "IDP_USERNAME_REQUIRED";
    String IDP_IDENTITY_ALREADY_EXISTS  = "IDP_IDENTITY_ALREADY_EXISTS";
    String IDP_IDENTITY_CREATION_FAILED = "IDP_IDENTITY_CREATION_FAILED";

    String IDP_GROUP_REQUIRED      = "IDP_GROUP_REQUIRED";
    String IDP_GROUP_NOT_FOUND     = "IDP_GROUP_NOT_FOUND";
    String IDP_ADD_TO_GROUP_FAILED = "IDP_ADD_TO_GROUP_FAILED";

    String IDP_FETCH_FAILED = "IDP_FETCH_FAILED";
}
