package org.romainlavabre.security.hydra;

import java.util.List;

/**
 * Administrates the machine to machine clients in Hydra, through its admin API. A client obtains its
 * tokens with the client_credentials grant, sending its id and secret in the body (client_secret_post).
 * <p>
 * Hydra keeps only a hash of the secret: it is returned once, on creation or rotation, and must never
 * be stored by the application.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface HydraClients {

    /**
     * @param name      Human readable name, eg the company name of the owner
     * @param scopes    Scopes the client may request, empty for none
     * @param audiences Audiences the client may request, eg marea
     * @return The client id generated by Hydra, with its secret in clear
     */
    Credentials create( String name, List< String > scopes, List< String > audiences );


    /**
     * Keeps the client id, only the secret changes. The former secret stops working at once.
     *
     * @return The new secret in clear
     */
    String rotateSecret( String clientId );


    /**
     * Best-effort: an already absent client is not an error.
     */
    void delete( String clientId );


    record Credentials( String clientId, String clientSecret ) {
    }
}
