package org.romainlavabre.security.hydra;

import org.romainlavabre.security.ory.Page;

import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Administrates the machine to machine clients in Hydra, through its admin API. A client obtains its
 * tokens with the client_credentials grant, sending its id and secret in the body (client_secret_post).
 * <p>
 * Hydra keeps only a hash of the secret: it is returned once, on creation or rotation, and must never
 * be stored by the application.
 * <p>
 * Every id is checked before being put in a URL: an unsafe one is refused with a 400.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface HydraClients {

    /**
     * @param name      Human readable name, eg the company name of the owner
     * @param scopes    Scopes the client may request, empty for none
     * @param audiences Audiences the client may request, eg marea
     * @return The client id generated by Hydra, with its secret in clear
     */
    Credentials create( String name, List< String > scopes, List< String > audiences );


    /**
     * Same as create( name, scopes, audiences ), with the metadata set at once.
     *
     * @param metadata Data the application reads back, eg the role it grants. Null for none.
     */
    Credentials create( String name, List< String > scopes, List< String > audiences, Map< String, Object > metadata );


    /**
     * @param pageSize  1 to 500
     * @param pageToken Token of the page to read, null for the first one
     * @param name      Exact client_name to filter on, null for all
     */
    Page< HydraClient > list( int pageSize, String pageToken, String name );


    /**
     * @return Empty when Hydra does not know this id
     */
    Optional< HydraClient > find( String clientId );


    /**
     * Replaces every scope of the client. Tokens already issued keep theirs until they expire.
     */
    void updateScopes( String clientId, List< String > scopes );


    /**
     * Replaces every audience of the client. Tokens already issued keep theirs until they expire.
     */
    void updateAudiences( String clientId, List< String > audiences );


    /**
     * Replaces the whole metadata of the client.
     */
    void replaceMetadata( String clientId, Map< String, Object > metadata );


    /**
     * Keeps the client id, only the secret changes. The former secret stops working at once.
     *
     * @return The new secret in clear
     */
    String rotateSecret( String clientId );


    /**
     * Best-effort: an already absent client is not an error.
     */
    void delete( String clientId );


    record Credentials( String clientId, String clientSecret ) {
    }
}
