package org.romainlavabre.security.identity;

import java.util.Map;

/**
 * Creates an identity in Kratos, through its admin API.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface CreateIdentity {

    /**
     * The email is the login identifier, and is marked as verified.
     *
     * @return The identity id generated by Kratos, which is the sub of its tokens
     */
    String create( String email );


    /**
     * Same as create( email ), with the metadata_admin set at once.
     *
     * @param metadataAdmin Data only the admin API reads, eg the role the application grants. Null for none.
     */
    String create( String email, Map< String, Object > metadataAdmin );
}
