package org.romainlavabre.security.identity;

import java.util.List;
import java.util.Map;

/**
 * Creates an identity in the AWS Cognito user pool, as an administrator.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface CreateIdentity {

    /**
     * The username stands for the email of the identity, which is marked as verified.
     *
     * @return The sub generated by AWS Cognito.
     */
    String create( String username );


    /**
     * The username stands for the email of the identity, which is marked as verified.
     *
     * @param groups Groups the identity is added to, they must already exist in the user pool.
     * @return The sub generated by AWS Cognito.
     */
    String create( String username, List< String > groups );


    /**
     * @param attributes Cognito user attributes, eg email, email_verified, phone_number, or any custom: prefixed one.
     * @return The sub generated by AWS Cognito.
     */
    String create( String username, Map< String, String > attributes );


    /**
     * @param attributes Cognito user attributes, eg email, email_verified, phone_number, or any custom: prefixed one.
     * @param groups     Groups the identity is added to, they must already exist in the user pool.
     * @return The sub generated by AWS Cognito.
     */
    String create( String username, Map< String, String > attributes, List< String > groups );
}
