package org.romainlavabre.security.identity;

/**
 * Creates an identity in Kratos, through its admin API. Kratos only knows the email: roles belong to
 * the application.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface CreateIdentity {

    /**
     * The email is the login identifier, and is marked as verified.
     *
     * @return The identity id generated by Kratos, which is the sub of its tokens
     */
    String create( String email );
}
