package org.romainlavabre.security.identity;

/**
 * Reads an identity from Kratos, through its admin API.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface FetchIdentity {

    /**
     * @return The identity id generated by Kratos, or null when no identity has this email as identifier.
     */
    String fetchSubByEmail( String email );
}
