package org.romainlavabre.security.identity;

/**
 * Reads an identity from the AWS Cognito user pool, as an administrator.
 *
 * @author Romain Lavabre <romain.lavabre@proton.me>
 */
public interface FetchIdentity {

    /**
     * The username stands for the email of the identity.
     *
     * @return The sub generated by AWS Cognito, or null when no identity matches the email.
     */
    String fetchSubByEmail( String email );
}
